### ISSUE TITLE
The password for node 'Lava Test' is invalid.

### ISSUE THREAD

**Issue by abdullahnas43** [ChocoMeow/Vocard#21]
Hello good afternoon, I get the error I wrote:

Node Lava Test is not able to connect! - Reason: The password for node 'Lava Test' is invalid.

Can you help me?

**Comment by abdullahnas43** [comment]
and how active my dashboard (web dashboard) i create linux (ubuntu) server.

**Comment by ChocoMeow** [comment]
> Hello good afternoon, I get the error I wrote:
> 
> Node Lava Test is not able to connect! - Reason: The password for node 'Lava Test' is invalid.
> 
> Can you help me?

The error provided are quite straightforward. It has been indicated that the password entered is invalid. Therefore, please ensure that you’re entering the correct password.

**Comment by Monster-Bunny** [comment]
:)

**Comment by ChocoMeow** [comment]
> and how active dashboard (web dashboard) i in a create linux (ubuntu) server.

I recommend starting by watching this video: https://youtu.be/5Y5GPO95uxE?si=jCGTxU2v0oM6KWMd

The setup process is identical, with one key difference: you need to modify the host IP from ‘127.0.0.1’ to ‘0.0.0.0’ in web app.py. This change will enable network-wide access to your website. If still extra help feel free to join our Discord support server for more support.
