### ISSUE TITLE
Messages from other bots

### ISSUE THREAD

**Issue by en0o0n** [ChocoMeow/Vocard#23]
Hello there,

i must say this music bot is amazing.
There is a feature i need, to make the bot listen to messages from other bots.

I tried to remove if message.author.bot from on_message
but the music bot still ignore messages from other bots

Can you please help me with this.

Best regards,
En0o0n

**Comment by ChocoMeow** [comment]
have you enabled message_content intent for your bot?

**Comment by en0o0n** [comment]
Thanks for the fast reply.
Yes i did:
![image](https://github.com/ChocoMeow/Vocard/assets/114078231/5ffc88b4-e270-4ada-afb7-e9ab046cf3f8)

**Comment by ChocoMeow** [comment]
Have you tried to print the message from the on_message? it returns none or something else

**Comment by en0o0n** [comment]
Yes i have tried to print messages from other bots and it display it correctly but still music bot still ignoring it :

Message received from Writer#1622 (Bot: True): -play sia

Playing music with normal user "-play sia" works

**Comment by ChocoMeow** [comment]
Can you show the code of your on_message function?

**Comment by en0o0n** [comment]
i just edit the last message above

**Comment by ChocoMeow** [comment]
it works for me

**Comment by en0o0n** [comment]
as you can see the normal user works but the bot dont haha and i have the same code
![image](https://github.com/ChocoMeow/Vocard/assets/114078231/8039dcf3-3fb4-46e9-8c6a-c80954fa3780)

what else should i do?

**Comment by ChocoMeow** [comment]
I have tested again and it works fine

![image](https://github.com/ChocoMeow/Vocard/assets/94597336/5568e137-b7d3-424e-b4cc-1943a4a23ee2)
![image](https://github.com/ChocoMeow/Vocard/assets/94597336/498ebdca-4254-4935-9d0b-6d0548246418)

```py
async def on_message(self, message: discord.Message, /) -> None:
        # if message.author.bot or not message.guild:
        #     return False

        if self.user.id in message.raw_mentions and not message.mention_everyone:
            prefix = await self.command_prefix(self, message)
            if not prefix:
                return await message.channel.send("I don't have a bot prefix set.")
            await message.channel.send(f"My prefix is `{prefix}`")

        print(message.content)
        await self.process_commands(message)
       ```

**Comment by en0o0n** [comment]
U are trying as Choco, its a normal user not an "app" or "bot"

**Comment by ChocoMeow** [comment]
make sure your bot has permission to read messages from your channel

**Comment by en0o0n** [comment]
The music bot is administrator 
and it read messages from the channel if i wrote it as a normal user 
But when i write messages as another bot then it ignores it

**Comment by ChocoMeow** [comment]
the message "No voice channel to connect. Please either provide one or join one." are send from the bot

**Comment by en0o0n** [comment]
Yeah i understand, can please try to play a song like senden "!p test" from a bot not from Choco

**Comment by ChocoMeow** [comment]
oh, you are talking about running a command by a bot. Of course, it is not working because discord.py is not allowed. in the process commands function it will bypass all the bot message

**Comment by en0o0n** [comment]
how can i avoid that :c?

**Comment by ChocoMeow** [comment]
you can modify the process_commands function in discord.py module

https://github.com/Rapptz/discord.py/blob/0e58a927ddbc300a17ef0137d948faa659565313/discord/ext/commands/bot.py#L1403

**Comment by en0o0n** [comment]
oh wait no u can edit that in the main.py
I just added explicit command invocation and now it worksssss

**Comment by ChocoMeow** [comment]
good to hear that :D

**Comment by en0o0n** [comment]
Thanks for your answers, talking helps always ^^
And thanks for the great music bot.
Can i ask another feature here or shall i make a new iissue for it?

**Comment by ChocoMeow** [comment]
You are welcome!

I generally prefer using Discord. however, since GitHub is more familiar to you, let’s create a separate issue there to discuss another topic.
