### ISSUE TITLE
Use Python Virtual Environment in the Docker Image.

### ISSUE THREAD

**Issue by DaanSelen** [ChocoMeow/Vocard#24]
Hello, I would like to ask if there would be a benefit of installing the dependencies using a Virtual Environment in the Dockerfile.

And also to upload this image to a registry.

For what purpose does the docker-compose.yml have multiple services? Are they needed for operation of Vocard?

**Comment by Azarath7** [comment]
Hello! I have been trying to figure out what you've meant by "installing the dependencies using virtual environment in a Dockerfile". I didn't get it... Please explain. As of services in docker-compose - well, both lavalink and mongo are optional, and used for selfhosting those services(you can build the bot without selfhosting them), but they are mandatory for the bot to work, so I strongly advise you to have them in your build, unless you are willing to use public lavalink servers(which are unstable) or free cloud storage(cloud mongodb was working fine for me so far)

**Comment by DaanSelen** [comment]
I mean getting the Python dependencies like I did in this repo: https://github.com/DaanSelen/WGDashboard-dockerized/tree/main/docker

venv? If you know the package?

**Comment by Azarath7** [comment]
Oh, I get it now. Yes, I think it might be better than what we have now. Now all the required libraries are installed from _requirements.txt_ on the host machine. Installing them locally within the container would be better. Docker files were written by me as I was learning and had no experience with Docker at that moment. I want to make Vocard Dashboard work in Docker, it is another separate service, unfortunately, I won't have access to my pc until the end of June.

**Comment by Azarath7** [comment]
Oh, I get it now. Yes, I think it might be better than what we have now. Now all the required libraries are installed from _requirements.txt_ on the host machine. Installing them locally within the container would be better. Docker files were written by me as I was learning and had no experience with Docker at that moment. I want to make Vocard Dashboard work in Docker, it is another separate service, unfortunately, I won't have access to my pc until the end of June.

UPD On the second thought though, I've spoken to ChatGPT and it said the following: "The current Dockerfile installs dependencies directly in the Docker container using pip install -r requirements.txt, not on the host machine." So if that is the case, I do not see any benefit from installing dependencies using virtual environment, as it is not necessary and adds more complexity to a simple project. But I'm still learning, maybe I'm wrong?

**Comment by DaanSelen** [comment]
> So if that is the case, I do not see any benefit from installing dependencies using virtual environment, as it is not necessary and adds more complexity to a simple project. But I'm still learning, maybe I'm wrong?

You might be right on this, it would add extra complexity without specifically needing it. I am just looking through certain source files and asking why decisions have been made.

Furthermore, do with my suggestions as you wish, but I see you using path bindings in your docker-compose.yml but they are not exposed as volumes within the Dockerfile. Is this because they are not essential? And perhaps a way to integrate the .env file directly into the Docker (compose) environment argument?

I look forward into hearing your opinion and reasons on these questions.

**Comment by Azarath7** [comment]
I have to add that many aspects of running this project in docker are unpolished/unfinished, so if you have suggestions or are willing to contribute - we would totally appreciate that! Thank you in advance!

**Comment by Azarath7** [comment]
Yeah, sure, go ahead! Thank you very much!

**Comment by Azarath7** [comment]
@DaanSelen how does this [docker-compose.yml](https://github.com/Azarath7/BB/blob/b70f9904add61f460ff84d1db989518f94cc2625/docker-compose.yml) look?

**Comment by ChocoMeow** [comment]
Please note that starting from version 2.6.9, all environment configurations will be consolidated within the settings.json file. Please be aware that the .env file and environment settings within docker-compose.yml will be deprecated in the upcoming release.
