### ISSUE TITLE
"This video is unavailable" v2.6,9b4

### ISSUE THREAD

**Issue by DudeShift** [ChocoMeow/Vocard#30]
Was using Vocard v2.6.8 when I originally had this issue but updated to latest beta v2.6.9b4 to see if that would fix it.

* When using the /play command and selecting one of the songs I get "This video is unavailable [common]" for every song I try.
* When using the /play command and entering in a spotify playlist I get "This video is unavailable! The next song will begin in the next 5 seconds.

This is on a fresh docker container install, with new spotify id, adjusting the password and the host for the lavalink server. Even tried using a non-self hosted lavalink server and still no luck. I am not self-hosting mongo as I am unsure of what to put as the name (url should be mongo:27017 since its locally hosted). 

This just started a day ago using v2.6.8. Any advice would be appreciated.

**Comment by Azarath7** [comment]
This is lavalink issue. Make sure you're using the latest version of lavalink.

**Comment by Azarath7** [comment]
```ghcr.io/azarath7/lavalink-jre22:latest```

You can try to use my lavalink image

**Comment by DudeShift** [comment]
@Azarath7 Thank you your fork worked great!
