### ISSUE TITLE
Why MongoDB?

### ISSUE THREAD

**Issue by f1amy** [ChocoMeow/Vocard#32]
Genuinely curious. Why not use a relational database, like PostgreSQL or MySQL?

**Comment by ChocoMeow** [comment]
I chose MongoDB for its flexibility and document-oriented structure, which makes it easier to adapt my data model as the bot evolves. The JSON-like format suits my needs for storing user and server settings, and MongoDB's scalability will help manage growth effectively.

**Comment by f1amy** [comment]
Thanks for the answer!
