### ISSUE TITLE
Little Error

### ISSUE THREAD

**Issue by MrDick004** [ChocoMeow/Vocard#42]
I have a problem with Deezer links (maybe from some other source as well). Basically the dynamic status of the current song does not appear in the voice channel, giving an error “can't convert non-string with explicit base”
The error occurs specifically for the file voicelink > placeholders.py line 93
It could also just be my problem, but does anyone have any idea what it is due to?

**Comment by iammonsterbunny** [comment]
Lavalink is responsible for playing Deezer

**Comment by ChocoMeow** [comment]
The error regarding voice status indicates that the source name is missing from the `sources_settings` section in your `settings.json ` file. Please check to ensure that the source name is correctly defined.
