### ISSUE TITLE
error

### ISSUE THREAD

**Issue by aqajjif** [ChocoMeow/Vocard#5]
need help 
![image](https://user-images.githubusercontent.com/98738008/233839813-5c509d19-b38e-443f-971f-f27065f8f781.png)

**Comment by ChocoMeow** [comment]
How did you get this error?

**Comment by ChocoMeow** [comment]
If you need future support welcome to join our discord server: https://discord.gg/wRCgB7vBQv

**Comment by aqajjif** [comment]
i don't i do like this video and i am getting this error https://www.youtube.com/watch?v=5Y5GPO95uxE&t=66s

**Comment by ChocoMeow** [comment]
Can you provide more information? like exception, current playing track.

**Comment by aqajjif** [comment]
log file
![image](https://user-images.githubusercontent.com/98738008/233841166-30e3fdfa-68a9-4010-bf8e-5555d4d3adf8.png)
![Uploading image.png…]()

**Comment by aqajjif** [comment]
![image](https://user-images.githubusercontent.com/98738008/233841390-50c547c5-a8dc-4cab-8243-ffdb45f4eff3.png)

**Comment by ChocoMeow** [comment]
i can't see any problem with these logs can you provide the track url that are your playing on

**Comment by ChocoMeow** [comment]
make your bot are not using default avatar @aqajjif
